# Generated by Django 4.2.1 on 2023-05-18 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precioCompra', models.IntegerField()),
                ('precioVenta', models.IntegerField()),
                ('detalleProducto', models.TextField(max_length=500)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('fechaCreacion', models.DateTimeField()),
                ('fechaModificacion', models.DateTimeField()),
                ('cantidad', models.IntegerField()),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.categoria')),
            ],
        ),
    ]
