# Generated by Django 4.2.1 on 2023-05-19 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedulaCliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=100)),
                ('telefonoCliente', models.IntegerField()),
                ('correoCliente', models.EmailField(max_length=100)),
                ('direccionCliente', models.CharField(max_length=300)),
                ('contraseñaCliente', models.CharField(max_length=30, verbose_name='Contraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('IDHotel', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombreHotel', models.TextField(max_length=100)),
                ('estrellasHotel', models.IntegerField()),
                ('costoHotel', models.DateTimeField()),
                ('serviciosHotel', models.TextField(max_length=500)),
                ('imagenHotel', models.ImageField(blank=True, null=True, upload_to='hoteles/')),
            ],
        ),
        migrations.CreateModel(
            name='reservaHotel',
            fields=[
                ('IDReservaHotel', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidadPersonasReservaHotel', models.IntegerField()),
                ('cantidadHabitacionesReservaHotel', models.TextField(max_length=500)),
                ('cedulaClienteReservaHotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='reservaVuelo',
            fields=[
                ('IDReservaVuelo', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidadPersonasReservaVuelo', models.IntegerField()),
                ('cedulaClienteReservaVuelo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('IDVuelo', models.BigAutoField(primary_key=True, serialize=False)),
                ('origenVuelo', models.CharField(max_length=100)),
                ('destinoVuelo', models.TextField(max_length=100)),
                ('fechaVuelo', models.DateField()),
                ('horaSalidaVuelo', models.TimeField()),
                ('horaLlegadaVuelo', models.TimeField()),
                ('sillasDisponibleVuelo', models.IntegerField()),
                ('costoVuelo', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
