# Generated by Django 4.2.1 on 2023-06-01 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_hotel_costohotel_alter_hotel_nombrehotel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservavuelo',
            name='IDVueloReservaVuelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.vuelo'),
        ),
    ]
