# Generated by Django 4.2.1 on 2023-06-01 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_reservavuelo_idvueloreservavuelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservahotel',
            name='IDHotelReservaHotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.hotel'),
        ),
    ]
