# Generated by Django 4.2.1 on 2023-06-13 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_hotel_imagenhotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cedulaCliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=100)),
                ('telefonoCliente', models.IntegerField()),
                ('correoCliente', models.EmailField(max_length=100)),
                ('direccionCliente', models.CharField(max_length=300)),
                ('contraseñaCliente', models.CharField(max_length=30, verbose_name='Contraseña')),
            ],
        ),
        migrations.AlterField(
            model_name='reservahotel',
            name='cedulaClienteReservaHotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.cliente'),
        ),
        migrations.AlterField(
            model_name='reservavuelo',
            name='cedulaClienteReservaVuelo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.cliente'),
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
